local speaker = data.raw["programmable-speaker"]["programmable-speaker"]
speaker.instruments[#speaker.instruments+1] = {
    name = "JRLines_sound",
    notes = {
		{name = "JR Ebisu", sound = {filename = "__JRLines__/sound_files/sound/JR_Ebisu.ogg"}},
		{name = "JR Ebisu vG", sound = {filename = "__JRLines__/sound_files/sound/JR_Ebisu_vG.ogg"}},
		{name = "JR Marina", sound = {filename = "__JRLines__/sound_files/sound/JR_Marina.ogg"}},
		{name = "JR Mellow Time", sound = {filename = "__JRLines__/sound_files/sound/JR_Mellow_Time.ogg"}},
		{name = "JR Moonstone", sound = {filename = "__JRLines__/sound_files/sound/JR_Moonstone.ogg"}},
		{name = "JR Osaka Loop 1", sound = {filename = "__JRLines__/sound_files/sound/JR_Osaka_Loop_1.ogg"}},
		{name = "JR Osaka Loop 2", sound = {filename = "__JRLines__/sound_files/sound/JR_Osaka_Loop_2.ogg"}},
		{name = "JR Osaka Loop 3", sound = {filename = "__JRLines__/sound_files/sound/JR_Osaka_Loop_3.ogg"}},
		{name = "JR Osaka Loop 4", sound = {filename = "__JRLines__/sound_files/sound/JR_Osaka_Loop_4.ogg"}},
		{name = "JR Rainy Station B", sound = {filename = "__JRLines__/sound_files/sound/JR_Rainy_Station_B.ogg"}},
		{name = "JR Rainy Station C", sound = {filename = "__JRLines__/sound_files/sound/JR_Rainy_Station_C.ogg"}},
		{name = "JR Sakura Sakura Ko vA", sound = {filename = "__JRLines__/sound_files/sound/JR_Sakura_Sakura_Ko_vA.ogg"}},
		{name = "JR Sakura Sakura Ko vB", sound = {filename = "__JRLines__/sound_files/sound/JR_Sakura_Sakura_Ko_vB.ogg"}},
		{name = "JR SF-1", sound = {filename = "__JRLines__/sound_files/sound/JR_SF-1.ogg"}},
		{name = "JR SF-10-31", sound = {filename = "__JRLines__/sound_files/sound/JR_SF-10-31.ogg"}},
		{name = "JR SH-1", sound = {filename = "__JRLines__/sound_files/sound/JR_SH-1.ogg"}},
		{name = "JR SH-1-1", sound = {filename = "__JRLines__/sound_files/sound/JR_SH-1-1.ogg"}},
		{name = "JR SH-2", sound = {filename = "__JRLines__/sound_files/sound/JR_SH-2.ogg"}},
		{name = "JR SH-2-1", sound = {filename = "__JRLines__/sound_files/sound/JR_SH-2-1.ogg"}},
		{name = "JR SH-3", sound = {filename = "__JRLines__/sound_files/sound/JR_SH-3.ogg"}},
		{name = "JR SH-3-1", sound = {filename = "__JRLines__/sound_files/sound/JR_SH-3-1.ogg"}},
		{name = "JR SH-4", sound = {filename = "__JRLines__/sound_files/sound/JR_SH-4.ogg"}},
		{name = "JR SH-5", sound = {filename = "__JRLines__/sound_files/sound/JR_SH-5.ogg"}},
		{name = "JR SH-5-1", sound = {filename = "__JRLines__/sound_files/sound/JR_SH-5-1.ogg"}},
		{name = "JR SH-5-2", sound = {filename = "__JRLines__/sound_files/sound/JR_SH-5-2.ogg"}},
		{name = "JR SH-6", sound = {filename = "__JRLines__/sound_files/sound/JR_SH-6.ogg"}},
		{name = "JR SH-7", sound = {filename = "__JRLines__/sound_files/sound/JR_SH-7.ogg"}},
		{name = "JR SH-8", sound = {filename = "__JRLines__/sound_files/sound/JR_SH-8.ogg"}},
		{name = "JR SH-8-1", sound = {filename = "__JRLines__/sound_files/sound/JR_SH-8-1.ogg"}},
		{name = "JR SH-9-1", sound = {filename = "__JRLines__/sound_files/sound/JR_SH-9-1.ogg"}},
		{name = "JR Station Notification", sound = {filename = "__JRLines__/sound_files/sound/JR_Station_Notification.ogg"}},
		{name = "JR Station Notification 2", sound = {filename = "__JRLines__/sound_files/sound/JR_Station_Notification_2.ogg"}},
		{name = "JR Station Notification 3", sound = {filename = "__JRLines__/sound_files/sound/JR_Station_Notification_3.ogg"}},
		{name = "JR Syncopation", sound = {filename = "__JRLines__/sound_files/sound/JR_Syncopation.ogg"}},
		{name = "JR Cielo Estrellado", sound = {filename = "__JRLines__/sound_files/sound/JR_Cielo_Estrellado.ogg"}},
		{name = "JR Commuter Train of Love", sound = {filename = "__JRLines__/sound_files/sound/JR_Commuter_Train_of_Love.ogg"}},
		{name = "JR First Spring Storm", sound = {filename = "__JRLines__/sound_files/sound/JR_First_Spring_Storm.ogg"}},
		{name = "JR Gota del Vient", sound = {filename = "__JRLines__/sound_files/sound/JR_Gota_del_Vient.ogg"}}
    }
}
